// Package entrypoint provides ABI bindings that are automatically generated by abigen for interacting with
// the EntryPoint contract. The entrypoint directory also contains helper modules for convenience.
package entrypoint

import (
	"github.com/go-logr/logr"
	"github.com/stackup-wallet/stackup-bundler/internal/logger"
)

var Logger logr.Logger

func InitLogger() {
	Logger = logger.NewZeroLogr().WithName("entrypoint")
}
